# Generated by Django 3.2.6 on 2021-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=12)),
                ('event_date', models.DateField(null=True)),
                ('event_location', models.CharField(max_length=10)),
            ],
        ),
    ]
