# Generated by Django 3.2.6 on 2021-08-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210817_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='comapany',
            new_name='company',
        ),
    ]
