# Generated by Django 3.2.6 on 2021-08-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_id', models.PositiveSmallIntegerField(null=True)),
                ('course_description', models.CharField(max_length=200)),
                ('course_trainer', models.CharField(max_length=40)),
                ('course_room', models.CharField(max_length=10)),
                ('course_email', models.EmailField(max_length=254, null=True)),
                ('course_channel', models.CharField(max_length=20)),
                ('course_calendar', models.DateField(null=True)),
                ('course_syllabus', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
    ]
