# Generated by Django 3.2.6 on 2021-08-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_syllabus',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
