# Generated by Django 3.2.6 on 2021-09-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_profile',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
