# Generated by Django 3.2.6 on 2021-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210815_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
