# Generated by Django 3.2.6 on 2021-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Prefer not to say')], max_length=8, null=True),
        ),
    ]
