# Generated by Django 3.2.6 on 2021-09-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('1', 'Rwandan'), ('2', 'Kenyan'), ('3', 'Ugandan'), ('4', 'SouthSudanes'), ('5', 'Sudanes')], max_length=15, null=True),
        ),
    ]
